Assignment-3 done
nikhil1-successive/js-training pull request #5
Opened 2023-10-05 04:52 UTC by nikhil1-successive

Kindly review my Assignment-3

2023-10-05 05:32 UTC, shahbaz-successive commented on Assignment-3/ques1.js
> +function add(n1, n2) {
Make an actual calculator that takes input and gives output depending upon operator provided.

2023-10-05 05:32 UTC, shahbaz-successive commented on Assignment-3/ques3.js
> +console.log(string);
Diamond pattern is different from actual required pattern

2023-10-05 05:33 UTC, shahbaz-successive requested changes
Please make feedback changes

2023-10-05 06:33 UTC, nikhil1-successive commented on Assignment-3/ques1.js
> +function add(n1, n2) {
Done

2023-10-05 06:34 UTC, nikhil1-successive commented on Assignment-3/ques3.js
> +console.log(string);
Done

2023-10-05 12:15 UTC, shahbaz-successive commented on Assignment-3/ques9.js
> +  if (n == 2) return 1;
We can write this in single if

2023-10-05 12:16 UTC, shahbaz-successive requested changes
Please do feedback changes

2023-10-05 17:22 UTC, nikhil1-successive commented on Assignment-3/ques9.js
> +  if (n == 2) return 1;
Done

2023-10-06 09:39 UTC, shahbaz-successive approved these changes
👍

2023-10-06 09:39 UTC, merged